### ISSUE TITLE
Add warnings about patching of Feeds module

### ISSUE THREAD

**Issue by pmasonids** [IDS-API/Drupal-modules#12]
This module silently patches the Feeds module. Add commentary to the README file and provide a warning notification on installation for users. Need to include a check that these files are writeable.

**Comment by joe-mcpherson** [comment]
Made Feeds dependency fixed to specific version 7.x-2.0-alpha9, so the user has to install that version. This version doesn't require a patch and doesn't error (the next version 7.x-2.0-beta1 throws an error). The README has been updated to reflect this version requirement.
