### ISSUE TITLE
Adding batch processing to data imports to retrieve all content

### ISSUE THREAD

**Issue by joe-mcpherson** [IDS-API/Drupal-modules#17]
Allow the ability to retrieve all content (up to an optional limit). This will happen on CRON process. This is a new feature that builds on being able to retrieve a specified number of new items. This is a requirement if we are to use this module to import all content into new CMS.

Required new options/text on admin page:
Periodic import
Number of content items to import in each call (N)
Number of documents and/or organisations to retrieve in each call to the IDS API. All new items will be imported. Default is 20.
Import limits
Maximum number of older content items to import   (None/All/N)
When set, all content will be imported until this limit is reached. Leave blank if you do not want to import older content. Default is 20.
Maximum age of pre-existing content items  
Only content up to this age will be imported, within the maximum number given above.

Notes on implementation from Pablo:
To set new variables (for instance the number of older items - idsimport_number_older) in the config form it should be done in idsimport/idsimport.admin.inc.

The number of items to retrieve, as well as the rest of the API parameters, are set in the constructor of the class IdsAssetsFetcher (which extends FeedsFetcher) - defined in idsimport/idsimport.feeds.inc
This class contains an object of class IdsApiRequest (defined in idsapi.request.inc) which is the one that calls the API.

You could consider this new variable 'idsimport_number_older', let's say, and another one that keeps track of the number of currently created items - 'idsimport_number_new_items', let's say - to construct the API query.

I'd have to think a bit more about it, but I think that in the function idsimport_import_now() (in idsimport/idsimport.admin.inc) you could check the number of items actually created/updated (checking the $source variable), update the number in 'idsimport_number_new_items' and keep calling $source->import() (which calls the fetcher, etc) until you get the number the you want.

Here there is a nice explanation/diagram of Feeds flow, which might help.
http://ygerasimov.com/feeds-cheatsheet-for-developers

**Comment by pmasonids** [comment]
Hi Joe Is this complete?

**Comment by joe-mcpherson** [comment]
Yes :)
